### ISSUE TITLE
TODO before launch

### ISSUE THREAD

**Issue by maxrothman** [eepMoody/open5e#28]
- [x] merge styling
- update readme
  - [x] make installation instructions for windows/mac
  - [x] add travis badge
- [x] make sure we're good on the RTD theme license
- [x] merge https://github.com/eepMoody/open5e/pull/30
